### ISSUE TITLE
Why Factor?

### ISSUE THREAD

**Issue by ghost** [julius383/asemica-factor#1]
Hey!

As someone who is also very interested in `linenoise/asemica`, I was surprised and even excited to see someone else was making a derived work from it. I don't know how far you are in the process of translation, but I have wondered why you chose an uncommon language to run this? Perl was probably chosen because of it's ability to handle regex and text manipulation quite well (because the whole cipher revolved around that).

**Comment by ghost** [comment]
My whole rationale is that if this were to be written in a more common and readable language, this could bring about a lot of fulfilled potential in her project! See, I attempted to do this on my own, thinking I could translate this into JavaScript, but I realized I was not skilled enough to accomplish the task as the script is very intricate. In addition, I feel like this, mixed with another cipher, could bring about some powerful encryption.

**Comment by julius383** [comment]
Hello,

I've been interested in both Factor and `linenoise/asemica` for a while and felt that using the former to try and re-implement the latter would be a good way to understand both. I've implemented most of the functionality except checking if a corpus file is good enough to use as a key (should be simple enough to do) and the custom format modes e-mail, poem etc (probably way harder). 

I also tried (and failed) to re-write it in a more approachable language (Python) previously but the mental strain of trying to understand both Perl and the cipher itself proved too much at the time. Using an uncommon language really forced me to try and understand how the cipher works internally before I could translate it so in the end I came away with a better understanding than was possible before.

I did write about the details of the asemica algorithm [here](https://saveandrun.com/posts/2020-04-15-implementing-asemica-a-markov-chain-based-cipher.html) which I hope serves to better explain how it works. Shoot me an e-mail any time with questions

**Comment by ForgivenNin** [comment]
Thanks for the reply!

I will say I have had the idea for some kind of GUI or way to make it more user-friendly, and earlier today I realized I could do so by making myself a little "command generator" for people to figure out what all they need to type into their terminals. After I make the first edition of it for `linenoise/asemica`, I would be more than happy to make one for `Factor`! All I would need is some sense of how it runs in comparison to the `Perl` version (lol).

I suppose my only question left for this issue is this: _If `Factor` made you look in depth to the inner workings of the program, and now you have understanding of it, why not give it another try with `Python`?_
